
export const members = {
    1: {
        profilephoto: "dvnimages/profile1.jpg",
        name: "Aradhya Gupta",
        role: "web Developer",
        joining: "OCTOBER 2025",
        mail: "email@gmail.com",
        github:"https://github.com/Aradhya89",
        linkedin:"#",
        twitter:"#",
        website:"#",
        bio: "Hello! I'm a final year Computer Science student passionate about artificial intelligence and robotics. Within the DVN Club, I lead the AI Automation team where we focus on creating intelligent agents for real-world problem solving.<br><br>My journey started with simple Python scripts, but I've since moved on to building complex neural networks and computer vision systems.I'm always looking for collaborators on open-source projects!",
        skill1:"Python",
        skill2:"TensorFlow",
        skill3:"OpenCV",
        skill4:"React.js",
        skill5:"Robotics Operating System (ROS)",
        skill6:"C++",
        skill7:"Data Visualization",
        skill8:"Project Management",
    },


    2: {
        profilephoto: "dvnimages/profile1.jpg",
        name: "Mohit Sharma",
        role: "Superwiser",
        joining: "NOVEMBER 2024",
        mail: "email id",
        github:"#",
        linkedin:"#",
        twitter:"#",
        portfolio:"#",
        bio: "Hello! I'm a final year Computer Science student passionate about artificial intelligence and robotics. Within the DVN Club,<br><br>I lead the AI Automation team where we focus on creating intelligent agents for real-world problem solving.My journey started with simple Python scripts, but I've since moved on to building complex neural networks and computer vision systems.I'm always looking for collaborators on open-source projects!",
        skill1:"Python",
        skill2:"TensorFlow",
        skill3:"OpenCV",
        skill4:"React.js",
        skill5:"Robotics Operating System (ROS)",
        skill6:"C++",
        skill7:"",
        skill8:"",
    },


    3: {
        profilephoto: "dvnimages/profile1.jpg",
        name: "Ayush Singh Kushwaha",
        role: "web developer",
        joining: "month year",
        mail: "email id",
        github:"#",
        linkedin:"#",
        twitter:"#",
        portfolio:"#",
        bio: "Hello! I'm a final year Computer Science student passionate about artificial intelligence and robotics. Within the DVN Club, I lead the AI Automation team where we focus on creating intelligent agents for real-world problem solving.My journey started with simple Python scripts, but I've since moved on to building complex neural networks and computer vision systems.I'm always looking for collaborators on open-source projects!",
        skill1:"Python",
        skill2:"TensorFlow",
        skill3:"OpenCV",
        skill4:"React.js",
        skill5:"Robotics Operating System (ROS)",
        skill6:"C++",
        skill7:"Data Visualization",
        skill8:"Project Management",
    },

    4: {
        profilephoto: "dvnimages/profile1.jpg",
        name: "Ram Prasad",
        role: "web developer",
        joining: "month year",
        mail: "email id",
        github:"#",
        linkedin:"#",
        twitter:"#",
        portfolio:"#",
        bio: "Hello! I'm a final year Computer Science student passionate about artificial intelligence and robotics. Within the DVN Club, I lead the AI Automation team where we focus on creating intelligent agents for real-world problem solving.My journey started with simple Python scripts, but I've since moved on to building complex neural networks and computer vision systems.I'm always looking for collaborators on open-source projects!",
        skill1:"Python",
        skill2:"TensorFlow",
        skill3:"OpenCV",
        skill4:"React.js",
        skill5:"Robotics Operating System (ROS)",
        skill6:"C++",
        skill7:"Data Visualization",
        skill8:"Project Management",
    }

};
